# -*- coding: utf-8 -*-
"""Assignmest1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QCZGavSx4_lsPvH1CZpthvUViKXjeRUU
"""

#Task-1

import pandas as pd
import numpy as np
data = np.random.randint(0, 10, size=(4, 4))
df = pd.DataFrame(data, columns=['A', 'B', 'C', 'D'])
df

#Task-2

df.columns = ['Random value 1', 'Random value 2', 'Random value 3', 'Random value 4']
df

#Task-3

df.describe()

#Task-4

null_values = df.isnull().sum()
data_types = df.dtypes

null_values

data_types

#Task-5

RandomValue2 = df.iloc[:, 1]
RandomValue3 = df.loc[:, 'Random value 3']
print("Using location method:")
print(RandomValue2)
print("\nUsing index location method:")
print(RandomValue3)